[package]
name = "tscp"
version = "0.1.0"
authors = ["Tom Kerrigan <tom.kerrigan@gmail.com>", "Kristopher Johnson <kris@kristopherjohnson.net>"]
edition = "2018"

[dependencies]
libc = "0.2"

[profile.release]
lto = true
